spring:
  main:
    allow-bean-definition-overriding: false
  cache:
    type: redis
  redis:
    host: localhost
    prot: 6379
  ratelimiter:
    enabled: true
    redis-address: redis://localhost:6300
    redis-password: 123456
server:
  port: 8080
sharding:
  jdbc:
    datasource:
      names: master,rslave01,rslave02
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3339/user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        maxPoolSize: 50
        minPoolSize: 1
      rslave01:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3340/user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        maxPoolSize: 50
        minPoolSize: 1
      rslave02:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3341/user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        maxPoolSize: 50
        minPoolSize: 1
    config:
      masterslave:
        load-balance-algorithm-type: random
        name: db1s2
        master-data-source-name: master
        slave-data-source-names: rslave01,rslave02
    props:
      sql:
        show: false
mybatis:
  datasource: datasource
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.login.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true